### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by no-coder123** [gurbaaz27/twitter-tracker-discord-bot#1]
hey, is there some way to contact you, i have some questions about that app

**Comment by gurbaaz27** [comment]
Hi! You can ask your query here itself if it's okay with you.


Else feel free to hit me up at gurbaazsn123@gmail.com

**Comment by no-coder123** [comment]
> Hi! You can ask your query here itself if it's okay with you.
> 
> Else feel free to hit me up at [gurbaazsn123@gmail.com](mailto:gurbaazsn123@gmail.com)

tyvm, I have contacted you

**Comment by gurbaaz27** [comment]
Cool! Lemme check that and reply you back
